version: '3'
services:
    heat-kg-notebook:
      image: jupyter/datascience-notebook
      volumes:
        - ./:/home/jovyan/work
      ports:
        - 8888:8888
      command: "start-notebook.sh"